var data={
"type": "FeatureCollection",
"name": "datos",
"crs": { "type": "name", "properties": { "name": "urn:ogc:def:crs:EPSG::4686" } },
"features": [
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 10, "modismo": "Porra", "idpalabras": 10, "palabra": "Cabeza", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 11, "modismo": "Patas", "idpalabras": 11, "palabra": "Pies", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 12, "modismo": "Banca", "idpalabras": 12, "palabra": "Silla", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 13, "modismo": "Pizarra", "idpalabras": 13, "palabra": "Tablero", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 14, "modismo": "Vaca", "idpalabras": 14, "palabra": "Vaca", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 15, "modismo": "Anteojos", "idpalabras": 15, "palabra": "Gafas", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 1, "nombre": "Pedro Álvarez", "edad": 35, "municipio": "SANTA ROSA DE OSOS", "departamento": "ANTIOQUIA", "municipio_procedencia": null, "departamento_procedencia": null, "idpersona": 1, "idpalabra": 16, "modismo": "Bolsa", "idpalabras": 16, "palabra": "Bolsa", "nombre_ent": "SANTA ROSA DE OSOS", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.439362786920256, 6.676085314553206 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 10, "modismo": "Testa", "idpalabras": 10, "palabra": "Cabeza", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 11, "modismo": "Pies", "idpalabras": 11, "palabra": "Pies", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 12, "modismo": "Sillón", "idpalabras": 12, "palabra": "Silla", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 13, "modismo": "Tablero", "idpalabras": 13, "palabra": "Tablero", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 14, "modismo": "Vaca", "idpalabras": 14, "palabra": "Vaca", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 15, "modismo": "Anteojos", "idpalabras": 15, "palabra": "Gafas", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 2, "nombre": "Ruth Rubio", "edad": null, "municipio": "JARDÍN", "departamento": "ANTIOQUIA", "municipio_procedencia": "GACHALÁ", "departamento_procedencia": "CUNDINAMARCA", "idpersona": 2, "idpalabra": 16, "modismo": "Empaque", "idpalabras": 16, "palabra": "Bolsa", "nombre_ent": "JARDÍN", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.818966024580249, 5.575085465379668 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 10, "modismo": "Tuste", "idpalabras": 10, "palabra": "Cabeza", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 11, "modismo": "Pezuñas", "idpalabras": 11, "palabra": "Pies", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 12, "modismo": "Silla", "idpalabras": 12, "palabra": "Silla", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 13, "modismo": "Tablero", "idpalabras": 13, "palabra": "Tablero", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 14, "modismo": "Vaca", "idpalabras": 14, "palabra": "Vaca", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 15, "modismo": "Gafas", "idpalabras": 15, "palabra": "Gafas", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } },
{ "type": "Feature", "properties": { "idinformante": 3, "nombre": "Andrés Perea", "edad": null, "municipio": "BELLO", "departamento": "ANTIOQUIA", "municipio_procedencia": "ACANDÍ", "departamento_procedencia": "CHOCÓ", "idpersona": 3, "idpalabra": 16, "modismo": "Chuspa", "idpalabras": 16, "palabra": "Bolsa", "nombre_ent": "BELLO", "departamen": "ANTIOQUIA" }, "geometry": { "type": "Point", "coordinates": [ -75.589661188809529, 6.358847489746553 ] } }
]
}
